version: "3"
services: 
  carte-master:
    image: zhanglv/kettle:8.1
    restart: always
    ports: 
    - "40000:40000"
    volumes: 
    - "/root/repo:/approot/repo"
    networks: 
    - ntkettle
    environment:
      CARTE_IS_MASTER: "Y"
      CARTE_MASTER_NAME: "carte-master"
      CARTE_MASTER_HOSTNAME: "carte-master"
  carte-slave:
    image: zhanglv/kettle:8.1
    restart: always
    ports: 
    - "8080:8080"
    volumes: 
    - "/opt/kettle/repo:/approot/repo"
    networks: 
    - ntkettle
    depends_on: 
    - carte-master
    environment:
      CARTE_IS_MASTER: "N"
      CARTE_INCLUDE_MASTERS: "Y"
      CARTE_MASTER_NAME: "carte-master"
      CARTE_MASTER_HOSTNAME: "carte-master"
networks: 
  ntkettle